yarnPath: .yarn/releases/yarn-4.6.0.cjs
# https://yarnpkg.com/configuration/yarnrc
nodeLinker: node-modules
# Define the registry to use when fetching packages.
npmRegistryServer: 'https://registry.yarnpkg.com'
